### ISSUE TITLE
Validation on all controllers/endpoints

### ISSUE THREAD

**Issue by notnullxyz** [notnullxyz/arid-grazer#5]
This is a concern, and I have wired it up to just work now.
It needs to be refactored to use Lumen's proper validation trait on the controllers...

Something like this in the controller endpoints.

```
#!php

        $this->validate($this->request, [
            'dest' => 'required|max:4',
            'email' => 'required'
        ]);
```
See https://lumen.laravel.com/docs/5.1/validation#available-validation-rules

**Comment by zacid** [comment]
There wasn't much to do here since I see you already took care of TokenController using Lumen's validation. I only added Lumen validation to the UserController to complete.
